### ISSUE TITLE
Add duplicate Taskcluster job to submit bouncer payload to new bouncer-admin

### ISSUE THREAD

**Issue by jbuck** [mozilla-services/bouncer-admin#25]
Once bouncer-admin has most of the other issues here fixes it should be deployed to production and have Taskcluster start submitting to it

**Comment by jbuck** [comment]
Will point at https://bounceradmin-default.stage.mozaws.net

**Comment by jbuck** [comment]
Being done in https://bugzilla.mozilla.org/show_bug.cgi?id=1573147

**Comment by AmanuelAaron** [comment]
Resolved in https://bugzilla.mozilla.org/show_bug.cgi?id=1573147
